### ISSUE TITLE
Spindown fails when one (or more) of the disks in .rc file doesn't exist

### ISSUE THREAD

**Issue by nick-s-b** [lynix/hdd-spindown.sh#2]
Hi,
I have a bunch of HDDs and I've noticed that when one of the disks is disconnected (i.e. missing from the system), hdd-spindown fails to spin down the rest of the disks and reports a failure. For example:

````
Sep 07 17:51:42 aar systemd[1]: Started Automatic Disk Standby.
Sep 07 17:51:42 aar hdd-spindown.sh[731]: Using 600s interval
Sep 07 17:51:42 aar hdd-spindown.sh[731]: recognized disk: ata-ST4000N00 --> sdd
Sep 07 17:51:42 aar hdd-spindown.sh[731]: error: device not found: 'ata-WDC_WD1001'
Sep 07 17:51:42 aar systemd[1]: hdd-spindown.service: Main process exited, code=exited, status=1/FAILURE
Sep 07 17:51:42 aar systemd[1]: hdd-spindown.service: Failed with result 'exit-code'.
````
Inside of the .rc file, I have a simple `CONF_DEV=` declaration that lists all disks by their ATA-ID.

In situations such as this, I'd assume that the program would ignore missing disks and just manage the rest of them. This would be especially useful if you have an external enclosure that might or might not be connected...

Thanks!

**Comment by lynix** [comment]
Thanks for your report! The feature you requested should be implemented by c411713, please try that version and report back if you encounter any issues.
