### ISSUE TITLE
Possibly solution for non-working spindown

### ISSUE THREAD

**Issue by iminet** [lynix/hdd-spindown.sh#7]
Hi All,

I've tried this script, and noticed that, if the external enclosure isn't supported officially by smartctl, the script won't work, even the other solutions.

Luckily the bypass trick is very simple. The root cause is that, the smartctl says: "Unknown USB bridge". This can be bypassed with the `-d sat` parameter.
I've replaced all of smartctl instances in your script like this: `smartctl -d sat`.
Voilá, the script is working so good.

May I suggest to implement this trick in the next release to stop wasting time by others who have officially unsupported enclosures like me?

Important! This trick will work only that case if `sudo hdparm -C /dev/sda` command also works, otherwise my suggestion won't get affected.

**Comment by lynix** [comment]
Thanks for the proposal, implemented in 5b89647.
